[versions]
kotlin = "1.9.23"
compose-plugin = "1.6.1"
gradle-tooling = "8.7"
junit = "5.10.2"

[libraries]
gradle-tooling = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle-tooling" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.12" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
