name: CI
on: push
jobs:
  check_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan check
  check_macos:
    needs: check_linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan check
  check_windows:
    if: false # Needs Gradle 8.8
    needs: check_linux
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan check
  build_linux:
    needs: check_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan packageZip
      - uses: actions/upload-artifact@v4
        with:
          name: linux-distribution
          path: gradle-client/build/dist
          if-no-files-found: error
  build_macos:
    needs: check_macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan packageReleaseDmg
      - uses: actions/upload-artifact@v4
        with:
          name: macos-distribution
          path: gradle-client/build/compose/binaries/main-release/dmg
          if-no-files-found: error
  build_windows:
    if: false # Needs Gradle 8.8
    needs: check_windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --stacktrace --scan packageZip
      - uses: actions/upload-artifact@v4
        with:
          name: windows-distribution
          path: gradle-client/build/dist
          if-no-files-found: error
