name: CI
on: push
jobs:
  validate_wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
  check_linux:
    needs: validate_wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan check
  check_macos:
    needs: check_linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan check
  check_windows:
    needs: check_linux
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan check
  build_linux:
    needs: check_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan packageReleaseDeb
      - uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: linux-distribution
          path: gradle-client/build/compose/binaries/main-release/deb
          if-no-files-found: error
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: gradle-client/build/compose/binaries/main-release/deb/**
  build_macos:
    needs: check_macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan packageReleaseDmg
      - uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: macos-distribution
          path: gradle-client/build/compose/binaries/main-release/dmg
          if-no-files-found: error
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: gradle-client/build/compose/binaries/main-release/dmg/**
  build_windows:
    needs: check_windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew --stacktrace --scan packageReleaseMsi
      - uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: windows-distribution
          path: gradle-client/build/compose/binaries/main-release/msi
          if-no-files-found: error
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: gradle-client/build/compose/binaries/main-release/msi/**
